server:
  error:
    whitelabel:
      enabled: false

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
      show-sql: true
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2

java:
  naming:
    factory:
      initial: org.jnp.interfaces.NamingContextFactory
    
logging:
  level:
    org:
      springframework:
        data: DEBUG